#!/usr/bin/env python3
import shodan
import sys

api_key = ""

commands = ["search", "host"]

if api_key == str(""):
    api_key = input('please enter your Shodan API Key now:')
    auth_file = open("auth.py", "w")
    auth_file.write("api_key = '%s'" % api_key)
    auth_file.close
    sys.exit(0)


api = shodan.Shodan(api_key)

try:
    if sys.argv[1] == "search" and sys.argv[2:]:
        try:
        	results = api.search(sys.argv[2])

        	print('Results found: %s' % results['total'])
        	for result in results['matches']:
                	print('IP: %s' % result['ip_str'])
                	print(result['data'])
                	print('') 

        except shodan.APIError as e:
            print('Error: %' % e)


    if sys.argv[1] == "host" and sys.argv[2:]:
        #Set the hostname to check
        host = api.host(sys.argv[2:])
        #Print general info
        print("IP: %s \n Organization: %s \n Operating System: %s" % (host['ip_str'], host.get('org', 'n/a'), host.get('os', 'n/a')))
        #Print all banners
        for item in host['data']:
                print("Port: %s \n Banner: %s \n" % (item['port'], item['data']))

except IndexError:
    print('syntax: ./shodan ' + str(commands) + ' search_keyword')

